let rows=[];
let columns=[];
let meta=[];
let currentMethod=null;

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=(n,d=3)=>Number.isFinite(n)?Number(n).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:0}):'—';
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length;
const variance=a=>{if(a.length<2)return NaN;const m=mean(a);return a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1)};
const sd=a=>Math.sqrt(variance(a));
const median=a=>{const b=[...a].sort((x,y)=>x-y),n=b.length;if(!n)return NaN;return n%2?b[(n-1)/2]:(b[n/2-1]+b[n/2])/2};
const quantile=(a,q)=>{const b=[...a].sort((x,y)=>x-y);if(!b.length)return NaN;const p=(b.length-1)*q,lo=Math.floor(p),hi=Math.ceil(p);return lo===hi?b[lo]:b[lo]+(b[hi]-b[lo])*(p-lo)};
const pearson=(x,y)=>{const n=Math.min(x.length,y.length);if(n<3)return NaN;const mx=mean(x),my=mean(y);let num=0,dx=0,dy=0;for(let i=0;i<n;i++){const a=x[i]-mx,b=y[i]-my;num+=a*b;dx+=a*a;dy+=b*b}return dx&&dy?num/Math.sqrt(dx*dy):NaN};
const pText=p=>!Number.isFinite(p)?'—':p<.001?'< .001':fmt(p,4);

function clean(v){return v===null||v===undefined?'':String(v).trim()}
function num(v){if(typeof v==='number'&&Number.isFinite(v))return v;const s=clean(v).replace(/\s/g,'');if(!s)return NaN;let normalized=s;if(/^[-+]?\d{1,3}(\.\d{3})*,\d+$/.test(s)) normalized=s.replace(/\./g,'').replace(',','.');else if(/^[-+]?\d+,\d+$/.test(s)) normalized=s.replace(',','.');const n=Number(normalized);return Number.isFinite(n)?n:NaN}
function uniqueValues(name){return [...new Set(rows.map(r=>clean(r[name])).filter(Boolean))]}
function numericValues(name){return rows.map(r=>num(r[name])).filter(Number.isFinite)}
function pairedNumeric(a,b){const x=[],y=[];rows.forEach(r=>{const xv=num(r[a]),yv=num(r[b]);if(Number.isFinite(xv)&&Number.isFinite(yv)){x.push(xv);y.push(yv)}});return{x,y}}

function inferColumn(name){const vals=rows.map(r=>clean(r[name])).filter(Boolean);const n=vals.length;const unique=new Set(vals).size;if(!n)return{name,type:'empty',valid:0,unique:0,missing:rows.length};
  const nums=vals.map(num).filter(Number.isFinite).length;
  if(nums/n>=.85)return{name,type:'numeric',valid:n,unique,missing:rows.length-n};
  const dates=vals.filter(v=>/[-/.]/.test(v)&&!Number.isNaN(Date.parse(v))).length;
  if(dates/n>=.85)return{name,type:'date',valid:n,unique,missing:rows.length-n};
  const avg=vals.reduce((s,v)=>s+v.length,0)/n;
  const cat=unique<=Math.max(12,Math.round(n*.2)) || (unique<=30&&avg<32);
  return{name,type:cat?'categorical':'text',valid:n,unique,missing:rows.length-n};
}

function diagnose(){meta=columns.map(inferColumn);const nNum=meta.filter(m=>m.type==='numeric').length,nText=meta.filter(m=>m.type==='text').length,nCat=meta.filter(m=>m.type==='categorical').length;
  let classification,reason;
  if(nText&&nNum){classification='Mixed';reason='The dataset contains both long-form text and numeric variables, so qualitative and quantitative analyses can be combined.'}
  else if(nText){classification='Qualitative';reason='Long-form text variables dominate the analyzable structure. Lexical exploration is available.'}
  else{classification='Quantitative';reason='The dataset is structured mainly as numeric and/or categorical variables suitable for statistical analysis.'}
  $('classification').textContent=classification;
  $('classificationReason').textContent=reason;
  $('datasetMetrics').innerHTML=[['Rows',rows.length],['Variables',columns.length],['Numeric',nNum],['Text',nText]].map(([a,b])=>`<div class="metric"><strong>${b}</strong><span>${a}</span></div>`).join('');
  $('variableTable').innerHTML=meta.map(m=>`<tr><td>${esc(m.name)}</td><td>${typePill(m.type)}</td><td>${m.valid}</td><td>${m.unique}</td><td>${m.missing}</td></tr>`).join('');
  $('diagnosisSection').classList.remove('hidden');
  buildRecommendations();
}
function typePill(t){const labels={numeric:'Numeric',categorical:'Categorical',text:'Text',date:'Date',empty:'Empty'};const cls=t==='text'?'text':t==='categorical'?'cat':t==='date'?'date':'';return `<span class="type-pill ${cls}">${labels[t]||t}</span>`}

function vars(type){return meta.filter(m=>m.type===type).map(m=>m.name)}
function categoryCandidates(min=2,max=15){return meta.filter(m=>m.type==='categorical'&&m.unique>=min&&m.unique<=max).map(m=>m.name)}

function buildRecommendations(){const numeric=vars('numeric'),categorical=vars('categorical'),text=vars('text'),binary=categoryCandidates(2,2),multi=categoryCandidates(3,10),cats=categoryCandidates(2,15);const rec=[];
  if(numeric.length)rec.push(['descriptive','Quantitative','Descriptive statistics','Summarise central tendency, dispersion, range and quartiles for numeric variables.']);
  if(categorical.length)rec.push(['frequency','Quantitative','Frequency analysis','Count categories and calculate percentages for a categorical variable.']);
  if(numeric.length>=2)rec.push(['correlation','Quantitative','Pearson correlation','Measure linear association among numeric variables using pairwise complete observations.']);
  if(numeric.length&&binary.length)rec.push(['ttest','Quantitative','Welch independent-samples t-test','Compare the mean of a numeric outcome between two independent groups without assuming equal variances.']);
  if(numeric.length&&multi.length)rec.push(['anova','Quantitative','One-way ANOVA','Compare a numeric outcome across three or more independent groups.']);
  if(cats.length>=2)rec.push(['chisq','Quantitative','Chi-square test of independence','Test association between two categorical variables and report Cramér’s V.']);
  if(numeric.length>=2)rec.push(['regression','Quantitative','Simple linear regression','Estimate a linear relationship between one numeric predictor and one numeric outcome.']);
  if(text.length)rec.push(['lexical','Qualitative','Lexical thematic scan','Explore frequent terms and bigrams and retrieve representative text passages.']);
  $('recommendGrid').innerHTML=rec.map(([id,tag,title,desc])=>`<article class="recommend"><span class="tag">${tag}</span><h3>${title}</h3><p>${desc}</p><button data-method="${id}">Use this analysis</button></article>`).join('');
  $('recommendGrid').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>selectMethod(b.dataset.method)));
  $('recommendSection').classList.remove('hidden');
}

const methodInfo={
 descriptive:['Descriptive statistics','Summarise numeric variables.'],frequency:['Frequency analysis','Inspect category distributions.'],correlation:['Pearson correlation','Calculate pairwise linear correlations.'],ttest:['Welch independent-samples t-test','Compare a numeric outcome between exactly two independent groups.'],anova:['One-way ANOVA','Compare a numeric outcome across 3–10 groups.'],chisq:['Chi-square test of independence','Assess association between two categorical variables.'],regression:['Simple linear regression','Model a numeric outcome from one numeric predictor.'],lexical:['Lexical thematic scan','Explore recurrent terms, bigrams and representative passages.']
};
function opt(names){return names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}
function selectMethod(method){currentMethod=method;const numeric=vars('numeric'),categorical=vars('categorical'),text=vars('text'),binary=categoryCandidates(2,2),multi=categoryCandidates(3,10),cats=categoryCandidates(2,15);const [title,desc]=methodInfo[method];$('analysisIntro').textContent=`${title}: ${desc}`;let html=`<div class="method-note">${desc}</div>`;
  if(method==='descriptive')html+=`<div class="control-group"><label>Numeric variable</label><select id="v1"><option value="__all">All numeric variables</option>${opt(numeric)}</select></div>`;
  if(method==='frequency')html+=`<div class="control-group"><label>Categorical variable</label><select id="v1">${opt(categorical)}</select></div>`;
  if(method==='correlation')html+=`<div class="method-note">All numeric variables will be included in the correlation matrix. Pairwise complete cases are used.</div>`;
  if(method==='ttest')html+=`<div class="control-group"><label>Numeric outcome</label><select id="v1">${opt(numeric)}</select></div><div class="control-group"><label>Two-group variable</label><select id="v2">${opt(binary)}</select></div>`;
  if(method==='anova')html+=`<div class="control-group"><label>Numeric outcome</label><select id="v1">${opt(numeric)}</select></div><div class="control-group"><label>Grouping variable (3–10 groups)</label><select id="v2">${opt(multi)}</select></div>`;
  if(method==='chisq')html+=`<div class="control-group"><label>Row variable</label><select id="v1">${opt(cats)}</select></div><div class="control-group"><label>Column variable</label><select id="v2">${opt(cats)}</select></div>`;
  if(method==='regression')html+=`<div class="control-group"><label>Outcome (Y)</label><select id="v1">${opt(numeric)}</select></div><div class="control-group"><label>Predictor (X)</label><select id="v2">${opt(numeric)}</select></div>`;
  if(method==='lexical')html+=`<div class="control-group"><label>Text variable</label><select id="v1">${opt(text)}</select></div>`;
  html+=`<button class="run-btn" id="runBtn">Run analysis</button>`;$('analysisControls').innerHTML=html;$('analysisSection').classList.remove('hidden');$('resultPlaceholder').style.display='block';$('analysisResults').innerHTML='';$('runBtn').addEventListener('click',runCurrent);$('analysisSection').scrollIntoView({behavior:'smooth',block:'start'});
}

function runCurrent(){try{const a=$('v1')?.value,b=$('v2')?.value;if((currentMethod==='chisq'||currentMethod==='regression')&&a===b)throw new Error('Please choose two different variables.');let out='';
  if(currentMethod==='descriptive')out=runDescriptive(a);if(currentMethod==='frequency')out=runFrequency(a);if(currentMethod==='correlation')out=runCorrelation();if(currentMethod==='ttest')out=runTTest(a,b);if(currentMethod==='anova')out=runAnova(a,b);if(currentMethod==='chisq')out=runChiSquare(a,b);if(currentMethod==='regression')out=runRegression(a,b);if(currentMethod==='lexical')out=runLexical(a);
  $('resultPlaceholder').style.display='none';$('analysisResults').innerHTML=out;
 }catch(e){$('resultPlaceholder').style.display='none';$('analysisResults').innerHTML=`<div class="warning">${esc(e.message||e)}</div>`}}

function runDescriptive(selected){const names=selected==='__all'?vars('numeric'):[selected];const body=names.map(name=>{const a=numericValues(name);return `<tr><td>${esc(name)}</td><td>${a.length}</td><td>${fmt(mean(a))}</td><td>${fmt(sd(a))}</td><td>${fmt(median(a))}</td><td>${fmt(Math.min(...a))}</td><td>${fmt(quantile(a,.25))}</td><td>${fmt(quantile(a,.75))}</td><td>${fmt(Math.max(...a))}</td></tr>`}).join('');return `<div class="result-block"><h3>Descriptive statistics</h3><div class="table-wrap"><table class="result-table"><thead><tr><th>Variable</th><th>N</th><th>Mean</th><th>SD</th><th>Median</th><th>Min</th><th>Q1</th><th>Q3</th><th>Max</th></tr></thead><tbody>${body}</tbody></table></div></div><div class="interpretation">Use these summaries to inspect scale, spread, possible outliers and data-entry issues before inferential testing.</div>`}
function runFrequency(name){const vals=rows.map(r=>clean(r[name])).filter(Boolean),n=vals.length;const map={};vals.forEach(v=>map[v]=(map[v]||0)+1);const arr=Object.entries(map).sort((a,b)=>b[1]-a[1]);return `<div class="result-block"><h3>${esc(name)} — frequency distribution</h3><div class="table-wrap"><table><thead><tr><th>Category</th><th>N</th><th>%</th></tr></thead><tbody>${arr.map(([k,c])=>`<tr><td>${esc(k)}</td><td>${c}</td><td>${fmt(c/n*100,1)}</td></tr>`).join('')}</tbody></table></div></div>`}
function runCorrelation(){const names=vars('numeric');if(names.length<2)throw new Error('At least two numeric variables are required.');const cells=names.map(rn=>`<tr><td>${esc(rn)}</td>${names.map(cn=>{const p=pairedNumeric(rn,cn);return `<td>${fmt(pearson(p.x,p.y),3)}</td>`}).join('')}</tr>`).join('');return `<div class="result-block"><h3>Pearson correlation matrix</h3><div class="table-wrap"><table><thead><tr><th></th>${names.map(n=>`<th>${esc(n)}</th>`).join('')}</tr></thead><tbody>${cells}</tbody></table></div></div><div class="interpretation">Correlation describes linear association, not causation. Values approach +1 or −1 as linear association strengthens and approach 0 as it weakens.</div>`}
function runTTest(outcome,group){const levels=uniqueValues(group);if(levels.length!==2)throw new Error('The grouping variable must contain exactly two non-missing groups.');const groups=levels.map(l=>rows.filter(r=>clean(r[group])===l).map(r=>num(r[outcome])).filter(Number.isFinite));if(groups.some(g=>g.length<2))throw new Error('Each group needs at least two valid numeric observations.');const [a,b]=groups,n1=a.length,n2=b.length,m1=mean(a),m2=mean(b),v1=variance(a),v2=variance(b);const se=Math.sqrt(v1/n1+v2/n2),t=(m1-m2)/se;const df=(v1/n1+v2/n2)**2/(((v1/n1)**2)/(n1-1)+((v2/n2)**2)/(n2-1));const p=window.jStat?2*(1-jStat.studentt.cdf(Math.abs(t),df)):NaN;const pooled=Math.sqrt(((n1-1)*v1+(n2-1)*v2)/(n1+n2-2));const d=(m1-m2)/pooled;return `<div class="stat-cards"><div class="stat-card"><strong>${fmt(t)}</strong><span>Welch t</span></div><div class="stat-card"><strong>${fmt(df,2)}</strong><span>df</span></div><div class="stat-card"><strong>${pText(p)}</strong><span>p (two-sided)</span></div></div><div class="result-block"><h3>Group descriptives</h3><table><thead><tr><th>Group</th><th>N</th><th>Mean</th><th>SD</th></tr></thead><tbody><tr><td>${esc(levels[0])}</td><td>${n1}</td><td>${fmt(m1)}</td><td>${fmt(Math.sqrt(v1))}</td></tr><tr><td>${esc(levels[1])}</td><td>${n2}</td><td>${fmt(m2)}</td><td>${fmt(Math.sqrt(v2))}</td></tr></tbody></table></div><div class="interpretation">Mean difference = ${fmt(m1-m2)}; Cohen’s d = ${fmt(d)}. ${Number.isFinite(p)?(p<.05?'The two-sided test is statistically significant at α = .05.':'The two-sided test is not statistically significant at α = .05.'):'Load jStat to calculate the p-value.'}</div>`}
function runAnova(outcome,group){const levels=uniqueValues(group);if(levels.length<3)throw new Error('ANOVA requires at least three groups.');const gs=levels.map(l=>({l,a:rows.filter(r=>clean(r[group])===l).map(r=>num(r[outcome])).filter(Number.isFinite)})).filter(g=>g.a.length);const all=gs.flatMap(g=>g.a),grand=mean(all);let ssb=0,ssw=0;gs.forEach(g=>{const m=mean(g.a);ssb+=g.a.length*(m-grand)**2;ssw+=g.a.reduce((s,x)=>s+(x-m)**2,0)});const dfb=gs.length-1,dfw=all.length-gs.length;if(dfw<=0)throw new Error('Not enough observations for ANOVA.');const msb=ssb/dfb,msw=ssw/dfw,F=msb/msw,p=window.jStat?1-jStat.centralF.cdf(F,dfb,dfw):NaN,eta=ssb/(ssb+ssw);return `<div class="stat-cards"><div class="stat-card"><strong>${fmt(F)}</strong><span>F</span></div><div class="stat-card"><strong>${dfb}, ${dfw}</strong><span>df</span></div><div class="stat-card"><strong>${pText(p)}</strong><span>p</span></div></div><div class="result-block"><h3>Group descriptives</h3><table><thead><tr><th>Group</th><th>N</th><th>Mean</th><th>SD</th></tr></thead><tbody>${gs.map(g=>`<tr><td>${esc(g.l)}</td><td>${g.a.length}</td><td>${fmt(mean(g.a))}</td><td>${fmt(sd(g.a))}</td></tr>`).join('')}</tbody></table></div><div class="interpretation">η² = ${fmt(eta)}. ${Number.isFinite(p)?(p<.05?'At least one group mean differs statistically at α = .05; a suitable post-hoc procedure is needed to identify where.':'No statistically significant overall mean difference is detected at α = .05.'):'Load jStat to calculate the p-value.'}</div>`}
function runChiSquare(a,b){const rlev=uniqueValues(a),clev=uniqueValues(b);if(rlev.length<2||clev.length<2)throw new Error('Both variables need at least two categories.');const table=rlev.map(()=>clev.map(()=>0));rows.forEach(r=>{const x=clean(r[a]),y=clean(r[b]),i=rlev.indexOf(x),j=clev.indexOf(y);if(i>=0&&j>=0)table[i][j]++});const rt=table.map(r=>r.reduce((s,x)=>s+x,0)),ct=clev.map((_,j)=>table.reduce((s,r)=>s+r[j],0)),N=rt.reduce((s,x)=>s+x,0);let chi=0,small=0;table.forEach((r,i)=>r.forEach((obs,j)=>{const e=rt[i]*ct[j]/N;if(e<5)small++;if(e>0)chi+=(obs-e)**2/e}));const df=(rlev.length-1)*(clev.length-1),p=window.jStat?1-jStat.chisquare.cdf(chi,df):NaN,v=Math.sqrt(chi/(N*Math.min(rlev.length-1,clev.length-1)));const body=rlev.map((r,i)=>`<tr><td>${esc(r)}</td>${table[i].map(x=>`<td>${x}</td>`).join('')}<td>${rt[i]}</td></tr>`).join('');return `<div class="stat-cards"><div class="stat-card"><strong>${fmt(chi)}</strong><span>χ²</span></div><div class="stat-card"><strong>${df}</strong><span>df</span></div><div class="stat-card"><strong>${pText(p)}</strong><span>p</span></div></div><div class="result-block"><h3>Contingency table</h3><div class="table-wrap"><table><thead><tr><th>${esc(a)} \ ${esc(b)}</th>${clev.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Total</th></tr></thead><tbody>${body}</tbody></table></div></div><div class="interpretation">Cramér’s V = ${fmt(v)}. ${Number.isFinite(p)?(p<.05?'The categorical variables show a statistically significant association at α = .05.':'No statistically significant association is detected at α = .05.'):'Load jStat to calculate the p-value.'}</div>${small?`<div class="warning">${small} expected cell count(s) are below 5. The Pearson chi-square approximation may be unreliable; consider collapsing sparse categories or using an exact approach where appropriate.</div>`:''}`}
function runRegression(yName,xName){const {x,y}=pairedNumeric(xName,yName);if(x.length<3)throw new Error('At least three complete numeric pairs are required.');const mx=mean(x),my=mean(y);let sxx=0,sxy=0;for(let i=0;i<x.length;i++){sxx+=(x[i]-mx)**2;sxy+=(x[i]-mx)*(y[i]-my)}if(!sxx)throw new Error('The predictor has no variance.');const slope=sxy/sxx,intercept=my-slope*mx,preds=x.map(v=>intercept+slope*v),res=y.map((v,i)=>v-preds[i]),sse=res.reduce((s,e)=>s+e*e,0),sst=y.reduce((s,v)=>s+(v-my)**2,0),r2=1-sse/sst,se2=sse/(x.length-2),seSlope=Math.sqrt(se2/sxx),t=slope/seSlope,df=x.length-2,p=window.jStat?2*(1-jStat.studentt.cdf(Math.abs(t),df)):NaN,r=pearson(x,y);return `<div class="stat-cards"><div class="stat-card"><strong>${fmt(r2)}</strong><span>R²</span></div><div class="stat-card"><strong>${fmt(slope)}</strong><span>Slope</span></div><div class="stat-card"><strong>${pText(p)}</strong><span>Slope p</span></div></div><div class="result-block"><h3>Regression coefficients</h3><table><thead><tr><th>Term</th><th>Estimate</th><th>SE</th><th>t</th><th>p</th></tr></thead><tbody><tr><td>Intercept</td><td>${fmt(intercept)}</td><td>—</td><td>—</td><td>—</td></tr><tr><td>${esc(xName)}</td><td>${fmt(slope)}</td><td>${fmt(seSlope)}</td><td>${fmt(t)}</td><td>${pText(p)}</td></tr></tbody></table></div><div class="interpretation">N = ${x.length}; Pearson r = ${fmt(r)}. Estimated equation: ${esc(yName)} = ${fmt(intercept)} + ${fmt(slope)} × ${esc(xName)}. ${Number.isFinite(p)?(p<.05?'The slope differs statistically from zero at α = .05.':'The slope is not statistically different from zero at α = .05.'):'Load jStat to calculate the p-value.'}</div>`}

const stop=new Set(`a an and are as at be been being but by can could did do does doing for from had has have having he her hers herself him himself his how i if in into is it its itself may me might more most my myself no nor not of on once only or other our ours ourselves out over own same she should so some such than that the their theirs them themselves then there these they this those through to too under until up very was we were what when where which while who whom why will with would you your yours yourself yourselves ve veya ile için ama bir bu şu o da de mi mı mu mü çok daha en gibi kadar olan olarak ise çünkü ben sen biz siz onlar her hiç ne nasıl neden sonra önce arasında üzere göre var yok değil aynı kendi biri iki üç ile ancak hem`.split(/\s+/));
function tokenize(s){return String(s).toLocaleLowerCase('tr-TR').normalize('NFKC').replace(/https?:\/\/\S+/g,' ').replace(/[^\p{L}\p{N}\s'-]/gu,' ').split(/\s+/).map(w=>w.replace(/^[-']+|[-']+$/g,'')).filter(w=>w.length>2&&!stop.has(w)&&!/^[0-9]+$/.test(w))}
function runLexical(name){const docs=rows.map(r=>clean(r[name])).filter(Boolean);if(!docs.length)throw new Error('No usable text was found.');const freq={},bi={};docs.forEach(d=>{const t=tokenize(d);t.forEach(w=>freq[w]=(freq[w]||0)+1);for(let i=0;i<t.length-1;i++){const b=t[i]+' '+t[i+1];bi[b]=(bi[b]||0)+1}});const terms=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,20),bigrams=Object.entries(bi).filter(x=>x[1]>1).sort((a,b)=>b[1]-a[1]).slice(0,12);const top=terms.slice(0,5).map(x=>x[0]);const quotes=top.map(term=>{const hits=docs.filter(d=>tokenize(d).includes(term)).sort((a,b)=>a.length-b.length);return hits[0]?[term,hits[0]]:null}).filter(Boolean);return `<div class="stat-cards"><div class="stat-card"><strong>${docs.length}</strong><span>Text records</span></div><div class="stat-card"><strong>${terms.reduce((s,x)=>s+x[1],0)}</strong><span>Top-term mentions</span></div><div class="stat-card"><strong>${Object.keys(freq).length}</strong><span>Distinct terms</span></div></div><div class="result-block"><h3>Frequent terms</h3><div class="term-cloud">${terms.map(([w,c])=>`<span class="term">${esc(w)} · ${c}</span>`).join('')}</div></div><div class="result-block"><h3>Frequent bigrams</h3>${bigrams.length?`<div class="term-cloud">${bigrams.map(([w,c])=>`<span class="term">${esc(w)} · ${c}</span>`).join('')}</div>`:'<p>No repeated bigrams were found.</p>'}</div><div class="result-block"><h3>Representative passages for leading terms</h3>${quotes.map(([t,q])=>`<div class="quote"><strong>${esc(t)}</strong><br>${esc(q)}</div>`).join('')}</div><div class="interpretation">This is a lexical exploration, not a completed thematic analysis. Use recurrent terms and passages as prompts for human coding, memoing, comparison and theme development.</div>`}

async function loadFile(file){$('fileStatus').textContent=`Reading ${file.name}…`;try{let wb;if(/\.csv$|\.tsv$|\.txt$/i.test(file.name)){const text=await file.text();wb=XLSX.read(text,{type:'string'});}else{const ab=await file.arrayBuffer();wb=XLSX.read(ab,{type:'array'});}const sheet=wb.Sheets[wb.SheetNames[0]];const data=XLSX.utils.sheet_to_json(sheet,{defval:''});if(!data.length)throw new Error('The selected sheet contains no data rows.');setRows(data,file.name)}catch(e){$('fileStatus').textContent=`Could not read file: ${e.message}`}}
function setRows(data,label){rows=data;columns=[...new Set(data.flatMap(r=>Object.keys(r)))];$('fileStatus').textContent=`Loaded ${label}: ${rows.length} rows × ${columns.length} variables.`;diagnose()}

$('fileInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)loadFile(f)});
const dz=$('dropzone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)loadFile(f)});
$('sampleBtn').addEventListener('click',()=>{const channels=['Online','Store'],regions=['North','Central','South'];const comments=['Fast delivery and very easy ordering','Customer service solved my problem quickly','The app is useful but checkout feels confusing','Good value and reliable service','Delivery was late and communication was weak','Simple interface and helpful support','Product quality was excellent','The process was difficult and slow'];const data=Array.from({length:48},(_,i)=>{const age=22+(i*7)%39,sat=3+((i*13)%8)/2,loy=Math.min(10,Math.max(1,sat*1.35+((i%5)-2)*.45));return{age,satisfaction:Number(sat.toFixed(1)),loyalty:Number(loy.toFixed(1)),channel:channels[i%2],region:regions[i%3],comment:comments[i%comments.length]}});setRows(data,'built-in sample dataset')});
